// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_prestige_1 = "CgkIpuTpvpsQEAIQIg"; // <GPGSID>
        public const string achievement_1000_coins_rate = "CgkIpuTpvpsQEAIQEw"; // <GPGSID>
        public const string achievement_5000_coins_rate = "CgkIpuTpvpsQEAIQFQ"; // <GPGSID>
        public const string achievement_50_room_fixes = "CgkIpuTpvpsQEAIQFg"; // <GPGSID>
        public const string achievement_2000_coins_rate = "CgkIpuTpvpsQEAIQFA"; // <GPGSID>
        public const string achievement_5_friends = "CgkIpuTpvpsQEAIQGg"; // <GPGSID>
        public const string achievement_5_gifts = "CgkIpuTpvpsQEAIQHQ"; // <GPGSID>
        public const string achievement_25_daily_misions = "CgkIpuTpvpsQEAIQIQ"; // <GPGSID>
        public const string achievement_level_5 = "CgkIpuTpvpsQEAIQDQ"; // <GPGSID>
        public const string achievement_3_stars = "CgkIpuTpvpsQEAIQEA"; // <GPGSID>
        public const string achievement_1_gift = "CgkIpuTpvpsQEAIQHA"; // <GPGSID>
        public const string achievement_prestige_5 = "CgkIpuTpvpsQEAIQJA"; // <GPGSID>
        public const string achievement_4_stars = "CgkIpuTpvpsQEAIQEQ"; // <GPGSID>
        public const string achievement_25_gifts = "CgkIpuTpvpsQEAIQHg"; // <GPGSID>
        public const string achievement_1000_room_fixes = "CgkIpuTpvpsQEAIQGA"; // <GPGSID>
        public const string achievement_5_stars = "CgkIpuTpvpsQEAIQEg"; // <GPGSID>
        public const string achievement_200_room_fixes = "CgkIpuTpvpsQEAIQFw"; // <GPGSID>
        public const string achievement_10_friends = "CgkIpuTpvpsQEAIQGw"; // <GPGSID>
        public const string achievement_level_50 = "CgkIpuTpvpsQEAIQDw"; // <GPGSID>
        public const string leaderboard_stars = "CgkIpuTpvpsQEAIQAg"; // <GPGSID>
        public const string achievement_3_friends = "CgkIpuTpvpsQEAIQGQ"; // <GPGSID>
        public const string achievement_level_20 = "CgkIpuTpvpsQEAIQDg"; // <GPGSID>
        public const string achievement_10_daily_misions = "CgkIpuTpvpsQEAIQIA"; // <GPGSID>
        public const string achievement_3_daily_misions = "CgkIpuTpvpsQEAIQHw"; // <GPGSID>
        public const string achievement_prestige_2 = "CgkIpuTpvpsQEAIQIw"; // <GPGSID>

}

